const images = [
    //　Brainrot Got
    { src: './img/cocofanto.png', value: 10, rarity: 'BrainrotGot' },
    { src: './img/tob.png', value: 25, rarity: 'BrainrotGot' },
    { src: './img/tralalero.png', value: 50, rarity: 'BrainrotGot' },
    { src: './img/Odin.png', value: 75, rarity: 'BrainrotGot' },
    { src: './img/chache.png', value: 80, rarity: 'BrainrotGot' },//机
    { src: './img/Espressona.png', value: 90, rarity: 'BrainrotGot' },
    { src: './img/lavaca.png', value: 100, rarity: 'BrainrotGot' },
    { src: './img/ecco.png', value: 110, rarity: 'BrainrotGot' },
    { src: './img/losvaguitas.png', value: 115, rarity: 'BrainrotGot' },
    { src: './img/bulbito.png', value: 120, rarity: 'BrainrotGot' },
    { src: './img/banana.png', value: 120, rarity: 'BrainrotGot' },
    { src: './img/chillin.png', value: 130, rarity: 'BrainrotGot' },
    { src: './img/trippi.png', value: 130, rarity: 'BrainrotGot' },//ピラニア
    { src: './img/brri.png', value: 135, rarity: 'BrainrotGot' },
    { src: './img/ciocco.png', value: 140, rarity: 'BrainrotGot' },
    { src: './img/brrestrh.png', value: 145, rarity: 'BrainrotGot' },
    { src: './img/torrtuginni.png', value: 150, rarity: 'BrainrotGot' },
    { src: './img/losbros.png', value: 155, rarity: 'BrainrotGot' },
    { src: './img/bambini.png', value: 160, rarity: 'BrainrotGot' },
    { src: './img/jiqi.png', value: 165, rarity: 'BrainrotGot' },//時計
    { src: './img/los.png', value: 170, rarity: 'BrainrotGot' },
    { src: './img/agarrini.png', value: 175, rarity: 'BrainrotGot' },//スコップ
    { src: './img/alessio.png', value: 180, rarity: 'BrainrotGot' },
    { src: './img/karkerkar.png', value: 190, rarity: 'BrainrotGot' },
    { src: './img/piccionetama.png', value: 200, rarity: 'BrainrotGot' },
    { src: './img/popcon.png', value: 205, rarity: 'BrainrotGot' },
    { src: './img/iipiccione.png', value: 210, rarity: 'BrainrotGot' },
    { src: './img/iimastodontico.png', value: 240, rarity: 'BrainrotGot' },
    { src: './img/jobjobjob.png', value: 220, rarity: 'BrainrotGot' },
    { src: './img/lassis.png', value: 230, rarity: 'BrainrotGot' },//姉妹
    { src: './img/malame.png', value: 250, rarity: 'BrainrotGot' },
    { src: './img/belugelo.png', value: 270, rarity: 'BrainrotGot' },
    { src: './img/miss.png', value: 300, rarity: 'BrainrotGot' },//ロケット

    //　Secret
    { src: './img/lostralaleritas.png', value: 200, rarity: 'Secret' },
    { src: './img/lostralaletitos.png', value: 200, rarity: 'Secret' },
    { src: './img/trenostruzzo.png', value: 300, rarity: 'Secret' },
    { src: './img/kravilino.png', value: 375, rarity: 'Secret' },
    { src: './img/losorcaleritos.png', value: 400, rarity: 'Secret' },
    { src: './img/loscouples.png', value: 450, rarity: 'Secret' },
    { src: './img/peely.png', value: 500, rarity: 'Secret' },
    { src: './img/piccione.png', value: 500, rarity: 'Secret' },
    { src: './img/pakrah_w.png', value: 550, rarity: 'Secret' },//鉛筆女
    { src: './img/pakrah.png', value: 600, rarity: 'Secret' },
    { src: './img/losjob.png', value: 700, rarity: 'Secret' },
    { src: './img/4000.png', value: 700, rarity: 'Secret' },//4000
    { src: './img/Babel.png', value: 800, rarity: 'Secret' },
    { src: './img/losisu.png', value: 900, rarity: 'Secret' },//ロス椅子
    { src: './img/orcalero.png', value: 1000, rarity: 'Secret' },
    { src: './img/frog.png', value: 1200, rarity: 'Secret' },
    { src: './img/ketchuru.png', value: 1500, rarity: 'Secret' },
    { src: './img/pothotspot.png', value: 2000, rarity: 'Secret' },
    { src: './img/21.png', value: 2100, rarity: 'Secret' },
    { src: './img/losmobilis.png', value: 2200, rarity: 'Secret' },
    { src: './img/nomyhotspot.png', value: 2500, rarity: 'Secret' },
    { src: './img/garamarama.png', value: 3000, rarity: 'Secret' },
    { src: './img/pirulitoita.png', value: 3500, rarity: 'Secret' },//飴
    { src: './img/iisacro.png', value: 4000, rarity: 'Secret' },
    { src: './img/chari2.png', value: 4500, rarity: 'Secret' },
    { src: './img/lagrande.png', value: 5000, rarity: 'Secret' },
    { src: './img/legolem.png', value: 6000, rarity: 'Secret' },
    { src: './img/67.png', value: 6700, rarity: 'Secret' },
    { src: './img/loshouse.png', value: 7000, rarity: 'Secret' },
    { src: './img/chicleteira.png', value: 8000, rarity: 'Secret' },
    { src: './img/pad.png', value: 10000, rarity: 'Secret' },
    { src: './img/dulduldul.png', value: 12000, rarity: 'Secret' },
    { src: './img/chinpanking.png', value: 25000, rarity: 'Secret' },
];
