const images = [
    //　Brainrot Got
    { src: './img/cocofanto.png', value: 10, sale: 0 },
    { src: './img/tob.png', value: 25, sale: 0 },
    { src: './img/tralalero.png', value: 50, sale: 0 },
    { src: './img/Odin.png', value: 75, sale: 0 },
    { src: './img/chache.png', value: 80, sale: 0 },//机
    { src: './img/Espressona.png', value: 90, sale: 0 },
    { src: './img/lavaca.png', value: 100, sale: 0 },
    { src: './img/ecco.png', value: 110, sale: 0 },
    { src: './img/losvaguitas.png', value: 115, sale: 0 },
    { src: './img/bulbito.png', value: 120, sale: 0 },
    { src: './img/banana.png', value: 120, sale: 0 },
    { src: './img/chillin.png', value: 130, sale: 0 },
    { src: './img/trippi.png', value: 130, sale: 0 },//ピラニア
    { src: './img/brri.png', value: 135, sale: 0 },
    { src: './img/ciocco.png', value: 140, sale: 0 },
    { src: './img/brrestrh.png', value: 145, sale: 0 },
    { src: './img/torrtuginni.png', value: 150, sale: 0 },
    { src: './img/losbros.png', value: 155, sale: 0 },
    { src: './img/bambini.png', value: 160, sale: 0 },
    { src: './img/jiqi.png', value: 165, sale: 0 },//時計
    { src: './img/los.png', value: 170, sale: 0 },
    { src: './img/agarrini.png', value: 175, sale: 0 },//スコップ
    { src: './img/alessio.png', value: 180, sale: 0 },
    { src: './img/karkerkar.png', value: 190, sale: 0 },
    { src: './img/piccionetama.png', value: 200, sale: 0 },
    { src: './img/popcon.png', value: 205, sale: 0 },
    { src: './img/iipiccione.png', value: 210, sale: 0 },
    { src: './img/iimastodontico.png', value: 240, sale: 0 },
    { src: './img/jobjobjob.png', value: 220, sale: 0 },
    { src: './img/lassis.png', value: 230, sale: 0 },//姉妹
    { src: './img/malame.png', value: 250, sale: 0 },
    { src: './img/belugelo.png', value: 270, sale: 0 },
    { src: './img/miss.png', value: 300, sale: 0 },//ロケット

    //　Secret
    { src: './img/lostralaleritas.png', value: 200, sale: 1 },
    { src: './img/lostralaletitos.png', value: 200, sale: 1 },
    { src: './img/trenostruzzo.png', value: 300, sale: 1 },
    { src: './img/kravilino.png', value: 375, sale: 1 },
    { src: './img/losorcaleritos.png', value: 400, sale: 1 },
    { src: './img/loscouples.png', value: 450, sale: 1 },
    { src: './img/peely.png', value: 500, sale: 1 },
    { src: './img/piccione.png', value: 500, sale: 1 },
    { src: './img/pakrah_w.png', value: 550, sale: 1 },//鉛筆女
    { src: './img/pakrah.png', value: 600, sale: 1 },
    { src: './img/losjob.png', value: 700, sale: 1 },
    { src: './img/4000.png', value: 700, sale: 1 },//4000
    { src: './img/Babel.png', value: 800, sale: 1 },
    { src: './img/losisu.png', value: 900, sale: 1 },//ロス椅子
    { src: './img/orcalero.png', value: 1000, sale: 1 },
    { src: './img/frog.png', value: 1200, sale: 1 },
    { src: './img/ketchuru.png', value: 1500, sale: 1 },
    { src: './img/pothotspot.png', value: 2000, sale: 1 },
    { src: './img/21.png', value: 2100, sale: 1 },
    { src: './img/losmobilis.png', value: 2200, sale: 1 },
    { src: './img/nomyhotspot.png', value: 2500, sale: 1 },
    { src: './img/garamarama.png', value: 3000, sale: 1 },
    { src: './img/pirulitoita.png', value: 3500, sale: 1 },//飴
    { src: './img/iisacro.png', value: 4000, sale: 1 },
    { src: './img/chari2.png', value: 4500, sale: 1 },
    { src: './img/lagrande.png', value: 5000, sale: 1 },
    { src: './img/legolem.png', value: 6000, sale: 1 },
    { src: './img/67.png', value: 6700, sale: 1 },
    { src: './img/loshouse.png', value: 7000, sale: 1 },
    { src: './img/chicleteira.png', value: 8000, sale: 1 },
    { src: './img/pad.png', value: 10000, sale: 1 },
    { src: './img/dulduldul.png', value: 12000, sale: 1 },
    { src: './img/chinpanking.png', value: 25000, sale: 1 },
];
